# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bab9be515a95a868b512492f7c70e77f563ca84bf344ddbfdf134dd63cdf2756db77a50c31a1d61204dbc4779ba9748c9a5ce9f4ff996f0b7844a2b3baea930

test:
  secret_key_base: 27b9c956d184f5659aa25afe06a6b658cc1b45d29ca8fc408604186d42d4f61d1a485facfa6bd23f32584b96fb3304cf3e4de832b1524ccf2ca1a92cfd245db1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
